### ISSUE TITLE
JS Files and Licensing

### ISSUE THREAD

**Issue by cdw9** [fusioncharts/django-wrapper#3]
Hi - I wanted to point out that the code in this repo contains the FusionCharts JS code in `fusioncharts/templates/static/fusioncharts/`.  It seems this may have been a mistake, as https://www.fusioncharts.com/django-charts/ says,  "You will still need to download and include FusionCharts in your page".

I am using it for non-commercial use, but I initially thought the JS files were included in the MIT licensing, since they were part of this package.

**Comment by uttamthapa** [comment]
Thanks. You are right. 
Removed the FusionCharts JS.

**Comment by ukthapa** [comment]
Thanks. You are right. 
Removed the FusionCharts JS.
